language: bash

dist: bionic
  
#services:
#  - docker

install:
  #- sudo apt-get update
  #- sudo apt-get install -yq mtr-tiny
  #- ping -c 4 www.google.de
  #- ping -c 4 git.haproxy.org
  #- curl https://ifconfig.co
  #- mtr -4 -c 10 -r 8.8.8.8
  #- mtr -4 -c 10 -r git.haproxy.org
  #- echo -e "GET / HTTP/1.1\nHost: git.haproxy.org\n" | nc -N git.haproxy.org 80
  #- bash netcat.sh

script:
  - git clone https://git.haproxy.org/git/haproxy-2.2.git/ haproxy
  #- git clone https://github.com/haproxy/haproxy.git haproxy
