language: bash

dist: bionic

#services:
#  - docker

install:
  - apt-get update
  - apt-get install -yq mtr-tiny
  #- ping -c 4 www.google.de
  #- ping -c 4 git.haproxy.org
  - mtr -4 -c 10 -r git.haproxy.org
  #- echo -e "GET / HTTP/1.1\nHost: git.haproxy.org\n" | nc -N git.haproxy.org 80
  #- bash netcat.sh

script:
  #- git clone http://git.haproxy.org/git/haproxy-2.1.git/ haproxy
  - git clone https://github.com/haproxy/haproxy.git haproxy
